### PR TITLE
Dynamic HostConfig

### PR DESCRIPTION
**Pull request by Curvel**
- Allows giving the ac a dynamic host config instead of a path to a constant file
- Add Brightness switch to Example App
- Add dynamic config reload on brightness switch

### CODE REVIEW

**Comment by beevelop** [comment]
photo_2020-06-02_16-59-37

Is the "Column background image" example supposed to look like that? Or should be blue color "shine through"?

**Comment by beevelop** [comment]
Can we add a quick example about using the HostConfig to the `README`?

**Comment by beevelop** [comment]
photo_2020-06-02_17-03-18
Unfortunately, same issue with the Weather Example card.

And we might have an issue with leaking memory in this changes. Got the following exception on the Pixel 2, when testing the changes:
```
E/AndroidRuntime(10557): Process: com.neohelden.flutter_adaptivecards, PID: 10557
E/AndroidRuntime(10557): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(10557): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(10557): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(10557): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(10557): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(10557): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(10557): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10557): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10557): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(10557): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 24896 free bytes and 24KB until OOM, target footprint 201326592, growth limit 201326592
E/AndroidRuntime(10557): 	at com.android.internal.util.FastXmlSerializer.<init>(FastXmlSerializer.java:86)
E/AndroidRuntime(10557): 	at com.android.internal.util.FastXmlSerializer.<init>(FastXmlSerializer.java:75)
E/AndroidRuntime(10557): 	at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:197)
E/AndroidRuntime(10557): 	at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:778)
E/AndroidRuntime(10557): 	at android.app.SharedPreferencesImpl.access$900(SharedPreferencesImpl.java:55)
E/AndroidRuntime(10557): 	at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:647)
E/AndroidRuntime(10557): 	at android.app.SharedPreferencesImpl.enqueueDiskWrite(SharedPreferencesImpl.java:666)
E/AndroidRuntime(10557): 	at android.app.SharedPreferencesImpl.access$100(SharedPreferencesImpl.java:55)
E/AndroidRuntime(10557): 	at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:585)
E/AndroidRuntime(10557): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1.doInBackground(MethodCallHandlerImpl.java:124)
E/AndroidRuntime(10557): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1.doInBackground(MethodCallHandlerImpl.java:121)
E/AndroidRuntime(10557): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(10557): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10557): 	... 4 more
I/r_adaptivecard(10557): Waiting for a blocking GC Alloc
I/r_adaptivecard(10557): Clamp target GC heap from 215MB to 192MB
I/r_adaptivecard(10557): WaitForGcToComplete blocked Alloc on ProfileSaver for 52.786ms
I/r_adaptivecard(10557): Starting a blocking GC Alloc
E/LoadTask(10557): OutOfMemory error loading stream
E/LoadTask(10557): java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 25192 free bytes and 24KB until OOM, target footprint 201326592, growth limit 201326592
E/LoadTask(10557): 	at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
E/LoadTask(10557): 	at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:633)
E/LoadTask(10557): 	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
E/LoadTask(10557): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:533)
E/LoadTask(10557): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:187)
E/LoadTask(10557): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
E/LoadTask(10557): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/LoadTask(10557): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/LoadTask(10557): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/LoadTask(10557): 	at java.lang.Thread.run(Thread.java:919)
I/Process (10557): Sending signal. PID: 10557 SIG: 9
Lost connection to device.
```

**Comment by Curvel** [comment]
The weather and the column background are fixed with the newest two commits. I will look into the other issues. @beevelop Thanks for the review!

**Comment by Curvel** [comment]
@beevelop Indeed the app crashed when due to a memory leak when switching the theme often. This bug should also exist on master, but you want notice it due to view rebuilds. Now the video player is disposed correctly and I wasn't able to produce a memory leak with this patch. (Checked with flutter DevTools)

**Comment by beevelop** [comment]
So tested and validated the changes on the Pixel 2 and the iPhone 7 with iOS 13.3; looks smooth and works properly. Awesome work @Curvel 🍻

**Pull request merged**
